mysql:
  username: "root"
  password: "password"
  path: "127.0.0.1:3306"
  db-name: "broadcast"
  config: "charset=utf8&parseTime=True&loc=Local"
  max-idle-conns: 20
  max-open-conns: 20
  log-mode: false

redis:
  addr: '127.0.0.1:6379'
  password: 'password'
  db: 0

system:
  env: "public"
  addr: 8002
  db-type: "mysql"
  mode: "debug"

jwt:
  signing-key: "your_key"

Log:
  path: "logs"
  name: "system.log"

email:
  host: ""
  port: 465
  user: ""
  pass: ""
  admin-user: ""
